name: GitHub Stats
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        run: curl -H "Authorization: token ${{ secrets.PAT_GITHUB_README_STATS }}" \
          "https://github-readme-stats.vercel.app/api?username=mikhail-ramirez&show_icons=true&count_private=true&hide_border=true"
